#!/bin/bash

# 132Mhz
rspeed=132000

# Downclock memory
echo -n "Switching to ECO-Mode: "
echo $rspeed > /sys/devices/platform/sunxi-ddrfreq/devfreq/sunxi-ddrfreq/userspace/set_freq && echo -n "RAM $rrspeed"

### Remap IRQs ###
# USB IRQs
echo 1 >/proc/irq/104/smp_affinity
echo 1 >/proc/irq/106/smp_affinity
echo 1 >/proc/irq/108/smp_affinity
echo 1 >/proc/irq/110/smp_affinity
# MMC IRQs
echo 1 >/proc/irq/92/smp_affinity
echo 1 >/proc/irq/93/smp_affinity
# Ethernet
echo 1 > /proc/irq/40/smp_affinity_list
echo -e "IRQ-remap"

# Stop 3 CPU cores
for coreid in `seq 1 3`; do
    echo 1 >/sys/devices/system/cpu/cpu${coreid}/online 2>/dev/null
done
echo -n "CPUCores "

echo