#!/bin/bash

rspeed=624000

# Increase memory speed
echo -n "Switching to Normal mode: "
echo $rspeed > /sys/devices/platform/sunxi-ddrfreq/devfreq/sunxi-ddrfreq/userspace/set_freq  2>/dev/null&& echo -n "RAM "

# Awake CPU cores
for coreid in `seq 1 3`; do
    echo 1 >/sys/devices/system/cpu/cpu${coreid}/online 2>/dev/null
done
echo -n "CPUCores "

### Remap IRQs ###
# USB IRQs
echo 2 >/proc/irq/104/smp_affinity
echo 2 >/proc/irq/106/smp_affinity
echo 4 >/proc/irq/108/smp_affinity
echo 8 >/proc/irq/110/smp_affinity
# MMC IRQs
echo 8 >/proc/irq/92/smp_affinity
echo 4 >/proc/irq/93/smp_affinity
# Ethernet
echo 1,2 > /proc/irq/40/smp_affinity_list
echo -e "IRQ-remap"

echo